### ISSUE TITLE
Question in Thompson Construction

### ISSUE THREAD

**Issue by ZuoyunZheng** [gaserashraf/Regex-to-NFA-DFA#1]
Hi gaserashraf,
nice work first and foremost.

Just have a quick question. In `ThompsonConstruction._construct_from_ast`, the case for `OrAstNode`, when generating the new `states` dict, the `final_state` is inserted twice. Is this a typo or is there some nuance to this that i'm not seeing? 

Thanks in advance! 

Regards,
Zheng.

**Comment by gaserashraf** [comment]
Hi  Zheng,
It's been a while since I code this, so I don't remember such details.

Thanks,
Gaser

**Comment by gaserashraf** [comment]
After taking a look, yes it's a typo.
Good catch!
